---
redisOperator:
  name: redis-operator
  imageName: radondb/redis-operator-arm
  imageTag: v1.2.6
  imagePullPolicy: Always
  imagePrefix: docker.io

  # Additional pod annotations
  podAnnotations: {}
  # Additional Pod labels (e.g. for filtering Pod by custom labels)
  podLabels:
    app.kubernetes.io/name: redis-operator
    
localRegistry: docker.io
namespaceOverride: radondb
redisImageName: redis-arm
redisExporterImageName: redis-exporter-arm
redisProxyImageName: predixy-arm
redisProxyExporterImageName: predixy-exporter-arm

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 500m
    memory: 500Mi

replicas: 1

serviceAccountName: redis-operator

priorityClassName: ""
nodeSelector: {}
tolerateAllTaints: false
tolerations: []
affinity: {}
